CREATE TABLE client
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(255),
    idnp       VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(255),
    function   VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE currency_dictionary
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_currency_dictionary PRIMARY KEY (id)
);

CREATE TABLE exchange_rate
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rate                   DECIMAL,
    exchange               DECIMAL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    employee_id            BIGINT                                  NOT NULL,
    currency_dictionary_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_exchange_rate PRIMARY KEY (id)
);

ALTER TABLE exchange_rate ADD CONSTRAINT FK_EXCHANGE_RATE_ON_CURRENCY_DICTIONARY FOREIGN KEY (currency_dictionary_id) REFERENCES currency_dictionary (id);
ALTER TABLE exchange_rate ADD CONSTRAINT FK_EXCHANGE_RATE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);


CREATE TABLE cash
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount_to_exchange DECIMAL,
    exchange_rate_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_cash PRIMARY KEY (id)
);

ALTER TABLE cash ADD CONSTRAINT FK_CASH_ON_EXCHANGE_RATE FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rate (id);


CREATE TABLE currency_exchange
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    amount_received DECIMAL,
    client_id       BIGINT                                  NOT NULL,
    employee_id     BIGINT                                  NOT NULL,
    cash_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_currency_exchange PRIMARY KEY (id)
);

ALTER TABLE currency_exchange ADD CONSTRAINT FK_CURRENCY_EXCHANGE_ON_CASH FOREIGN KEY (cash_id) REFERENCES cash (id);
ALTER TABLE currency_exchange ADD CONSTRAINT FK_CURRENCY_EXCHANGE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);
ALTER TABLE currency_exchange ADD CONSTRAINT FK_CURRENCY_EXCHANGE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);